### ISSUE TITLE
Update handlers to return error for gofiber v2 compatibility

### ISSUE THREAD

**Issue by circa10a** [ansrivas/fiberprometheus#14]
The current library is now incompatible with the new 2.0.0 release. The handlers need to return an error to work with v2. The README should also be updated as an example.

- [gofiber v2 changelog](https://github.com/gofiber/fiber/releases/tag/v2.0.0)

**Comment by ansrivas** [comment]
Thanks for the heads up, will fix and release soon.

**Comment by ansrivas** [comment]
Should work now with the new import path. 
https://github.com/ansrivas/fiberprometheus#example-using-v2
