### ISSUE TITLE
Possibility to run on a different port?

### ISSUE THREAD

**Issue by YashKumarVerma** [ansrivas/fiberprometheus#145]
is there any possibility to run the Prometheus server on a different port?
- i.e. run two handlers, one for HTTP requests and one dedicated for metrics endpoint
- also if I want to emit some custom metrics from other adapters, like redis exporter, what's the way forward

**Comment by ansrivas** [comment]
Hi @YashKumarVerma, 

>     * i.e. run two handlers, one for HTTP requests and one dedicated for metrics endpoint
1. In the current structure of fiberprometheus it can't be done unfortunately.

>     * also if I want to emit some custom metrics from other adapters, like redis exporter, what's the way forward
2. You will have to add your custom metric to the corresponding exporter for e.g something like [this](https://github.com/ansrivas/fiberprometheus/blob/58dc0172b4ba2efd41e0dbd1a5e4481eeb7d89ec/middleware.go#L104), you can send a PR to the maintainer to add a custom metric of your choice or fork and implement and use it.

Hope this clarifies.
