### ISSUE TITLE
Is it possible to separately collect parametrized routes?

### ISSUE THREAD

**Issue by Sobakaa** [ansrivas/fiberprometheus#146]
At present, as far as i can tell after a fix in https://github.com/ansrivas/fiberprometheus/issues/127, if i hit two url's `/v1/namespace/n1` and `/v1/namespace/n2` on a parametrized route `/v1/namespace/:n` those would be both bundled together into a metric with path `/v1/namespace/:n`.
I am, however, interested in frequency of hits to specific parametrized urls. I'd like to see them separated by a parametrized `path` label. So far,  the only way to do this i found is to change the way path is calculated in Middleware
```
path := string(ctx.Request().URI().Path())
```
Perhaps there is a way to do it without making a fork of your library and i just don't see it?

**Comment by gabzim** [comment]
be careful with that, if the parameter is an `id` or something with high cardinality, it can wreck your prometheus backend with high cardinality.

**Comment by ansrivas** [comment]
@Sobakaa in the current state of the lib you can not achieve it ( feel free to fork and tweak it according to your requirements ),
but as @gabzim rightly pointed out - the cardinality of the input path might be high and the generated metrics will not be very useful.

**Comment by Sobakaa** [comment]
@gabzim Thank you for the suggestion. In the immediate case i was looking to do it for i do not expect more than 3 varied paths, but i'll keep cardinality in mind for any future scenarios.
@ansrivas I see. I'm a novice with Go so i thought that maybe i was just not seeing something obvious.
