### ISSUE TITLE
ignore /metrics, /live and /ready path

### ISSUE THREAD

**Issue by kirankumar-grootan** [ansrivas/fiberprometheus#200]
is it possible to ignore /metrics, /live and /ready path from getting included in Prometheus metrics. its increasing `romhttp_metric_handler_requests_total` unnecessarily

```
promhttp_metric_handler_requests_total{code="200"} 33
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

**Comment by kirankumar-grootan** [comment]
and also a way to ignore other routes in future

**Comment by gaby** [comment]
@kirankumar-grootan Just submitted a PR to add support for skipping paths natively on this middleware.
