### ISSUE TITLE
Usage with fiber v3

### ISSUE THREAD

**Issue by goodpeanut** [ansrivas/fiberprometheus#212]
Hello,

I have tested and ready code which bumps the version to fiber v3.
I cannot push to this repo, I don't have permissions.

I'd like to contribute but I'm not sure how.

**Comment by drithh** [comment]
i think u can do pull request

**Comment by gaby** [comment]
@goodpeanut This middleware is being migrated to the GoFiber organization. Hold off for now

**Comment by gaby** [comment]
@mrusme Working on it, v3 is still under development. But I can do the migration for v2 in the meantime

**Comment by gaby** [comment]
@mrusme @drithh @goodpeanut The official v3 middleware has been released by the fiber team:

Release: https://github.com/gofiber/contrib/releases/tag/v3%2Fprometheus%2Fv0.0.1
Docs: https://github.com/gofiber/contrib/tree/main/v3/prometheus

The middleware is a complete rewrite, with many extra features from prometheus, including go/os metrics.
